export { default as ClassicTemplate } from './ClassicTemplate'
export { default as ModernTemplate } from './ModernTemplate'
export { default as MinimalTemplate } from './MinimalTemplate'
export { default as CreativeTemplate } from './CreativeTemplate'
export { default as ExecutiveTemplate } from './ExecutiveTemplate'
